apiVersion: v1
kind: ConfigMap
metadata:
  name: es-master-config
data:
  elasticsearch.yml: |
    ---
    xpack.security.enabled: "false"
    cluster.name: "sandbox-es"
    node.master: "true"
    node.data: "false"
    node.ml: "false"
    node.ingest: "false"
    node.name: ${HOSTNAME}
    node.max_local_storage_nodes: 3
    #processors: ${PROCESSORS}
    network.host: "_site_"
    path.data: "/data/data/"
    path.logs: "/data/log"
    path.repo: "data/repo"
    http.cors.enabled: "true"

    discovery.seed_hosts: ed
    cluster.initial_master_nodes: es-master-0,es-master-1,es-master-2

    cluster.routing.allocation.awareness.attributes: zone

    xpack.license.self_generated.type: "trial"
    xpack.security.http.ssl.enabled: "false"
    xpack.monitoring.collection.enabled: "true"

    xpack.security.transport.ssl.enabled: false
